# Generated by Django 5.2.6 on 2025-09-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageprompt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Prompt', 'verbose_name_plural': 'Image Prompts'},
        ),
        migrations.RemoveField(
            model_name='imageprompt',
            name='like',
        ),
    ]
